### ISSUE TITLE
y(t) = close(t)/close(t-1) or y(t) = close(t)/open(t)?

### ISSUE THREAD

**Issue by wassname** [ZhengyaoJiang/PGPortfolio#1]
Thanks for putting the code up. Can I ask for a minor clarification?

In the paper it said you have `y(t) = close(t)/open(t)` but in the code there is `y(t) = close(t)/close(t-1)`

The paper also divides the batch `X` by the `open(t)` (`X=M/open(t)`) but in the code it doesn't look like it's divided/scaled (`X=M`)?

[Heres](https://github.com/ZhengyaoJiang/PGPortfolio/blob/7bafedbf003e970bc3e69d806755a39955c2b274/pgportfolio/marketdata/datamatrices.py#L169) the code I'm talking about. I think the shape of M is (batch, features, coins, times) where features are ["close", "high", "low", "open"].

Have these things changes since the paper or am I misunderstanding something?

Thanks!

**Comment by ZhengyaoJiang** [comment]
Hi, nice to see you again.

> In the paper it said you have `y(t) = close(t)/open(t)` but in the code there is `y(t) = close(t)/close(t-1)`

I think in the article, what we want to express is `y(t) = close(t)/close(t-1)`.

> The paper also divides the batch `X` by the `open(t)` (`X=M/open(t)`) but in the code it doesn't look like it's divided/scaled (`X=M`)?

It's done in the tensorflow code(network.py) for saving memory.

**Comment by wassname** [comment]
Ah thanks for clarifying, that makes sense. 

Both I and @goolulusaurs (whos been working with me) misinterpreted that part of the paper so it might be worth considering a rephrase when you do arxiv version 2.

**Comment by ZhengyaoJiang** [comment]
> Both I and @goolulusaurs (who has been working with me) misinterpreted that part of the paper so it might be worth considering a rephrase when you do version 2 of the arxiv paper.

Yes, I agree.

**Comment by kumkee** [comment]
> In the paper it said you have y(t) = close(t)/open(t) but in the code there is y(t) = close(t)/close(t-1)

Quoting from our paper:
> For continuous markets, elements of v_t are the opening prices for Period t + 1 as well
as the closing prices for Period t.

That means we assumed open(t) = close(t-1) there.

**Comment by wassname** [comment]
Ah didn't see that, thanks.
