### ISSUE TITLE
Value error: the length of selected coins 0 is not equal to expected 11

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#10]
Hello, 
Thanks for the great work, i keep getting error message 

'the length of selected coins 0 is not equal to expected 11'
 when i start training using 
'python main.py --mode=train --processes=1'

Regards,

**Comment by ZhengyaoJiang** [comment]
Greetings.
Still, it looks like a problem of downloading data.
I will upload dataset to a online disk.

Regards
Zhengyao

**Comment by AhmMontasser** [comment]
Thanks very much :)

**Comment by ZhengyaoJiang** [comment]
Please check the first release where there is a Data.db file. Also, please make sure you've pulled the latest commit and set the `online` in input config to be `false`.

**Comment by AhmMontasser** [comment]
Thank you, i trained successfully

**Comment by redzhepdx** [comment]
@ZhengyaoJiang I am getting same error in lastest verison. Data.db in PGPortfolio/database folder and online parameter setted to false in input config file.
