### ISSUE TITLE
Low GPU-Usage while training

### ISSUE THREAD

**Issue by gomboappp** [ZhengyaoJiang/PGPortfolio#100]
i'm modifying the code for my personal usage for a while now, but encountered very low GPU-usage for training since i cloned the repository.
Training uses 2-5% at max. of the GPU (shown in nvidia-smi).
It occurs when using a single or multiply processes. Increasing the hard coded values in network.py above 0.2 also has no impact.

Correct drivers are installed, using a gtx 1080 on Ubuntu 18.04.
I'm using Tensorflow v. 1.8.0 and  NVIDIA UNIX x86_64 Kernel Module  390.67

Has anybody ran into the same problem, or has a solution for it?
Thanks

**Comment by DexHunter** [comment]
what about the memory usage?

**Comment by gomboappp** [comment]
Memory Usage was 0% - i figured out that my IDE destroyed my pip-installation of tensorflow. A native installation of tensorflow-gpu solved the problem for me.

GPU usage is now at 55%, Memory at 100% - I'm almost sure the bottleneck was produced by modifications. Thanks for your help, @DexHunter
