### ISSUE TITLE
problems about state representation `datametrices.py`

### ISSUE THREAD

**Issue by AchillesJJ** [ZhengyaoJiang/PGPortfolio#106]
In `marketdata/datametrices.py`, line `172`, there is a function `get_submatrix(self, ind)`. This function is suppose to gives the state representation for a given time index `ind`. Here, the state should be a history price(or return) between time period `[ind-window_size, ind]`. However, in `get_submatrix`, we have

    return self.__global_data.values[:, :, ind:ind+self._window_size+1]

which means it use future price(or return) to represent current state at time `ind`. Is there any explanation about this problem ?

**Comment by AchillesJJ** [comment]
@kumkee @DexHunter Thank you

**Comment by ZhengyaoJiang** [comment]
@AchillesJJ Thanks for your question.
Has your question been answered in private? If so, I'll close this issue.

**Comment by AchillesJJ** [comment]
No, but I know understand. Thanks
