### ISSUE TITLE
What is the meaning of the data?

### ISSUE THREAD

**Issue by zhouhao-learning** [ZhengyaoJiang/PGPortfolio#110]
Hello, I am paying attention to what you are doing. Although I have not seen the data you provided, I have seen that you have provided a method for downloading data in the code. Can you attach a data description file because I think The meaning of the data is very important for AI developers....
Thank You!

**Comment by dexhunter** [comment]
you can check the [release](https://github.com/ZhengyaoJiang/PGPortfolio/releases) for Data.db
