### ISSUE TITLE
train_summary.csv

### ISSUE THREAD

**Issue by marker1401** [ZhengyaoJiang/PGPortfolio#116]
Cant figure out how to interpret the data represented in the .csv file, due to formatting. Would it be possible to get some insight on how to interpret it, in order to make the file readable? Thanks. 

![image](https://user-images.githubusercontent.com/46245407/50547483-8295c280-0c3a-11e9-9f2f-455627613c6a.png)

**Comment by dexhunter** [comment]
you can just plot it? Or what do you suggest?

**Comment by marker1401** [comment]
no i mean i dont realise what is meant by all that

**Comment by dexhunter** [comment]
it's the results of a trained agents, code are [here](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/learn/tradertrainer.py#L226-L235)

**Comment by marker1401** [comment]
thanks!
