### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by srozov** [ZhengyaoJiang/PGPortfolio#12]
First of all, I'd like to thank you for your work! I was able to run the code in Windows, the only minor issue was to install some modules for python 3.5, had to find some unofficial wheels.
However, I couldn't make it run on MacOS X, it's crashing due to an unknown error (¨python quit unexpectedly¨). I know this is not officially supported, but I'd like to know if you have any hints on what might be the issue...
Here's what I already tried:
-Deleted .DS_Store files from all subdirectories (so that it passes the `if not str.isdigit(dir):` condition)
-Tried different python versions and clean environments
It fails to execute`TraderTrainer(config, save_path=save_path, device=device).train_net(log_file_dir=log_file_dir, index=index)`. The log file is created but remains empty... Do you think this has something to do with pathname issues in OS X or the python modules?

**Comment by srozov** [comment]
Ok, so apparently it crashes after the line `vol = self._polo.marketVolume()` in `coinlist.py`. Probably has something to do with the poloniex wrapper.

**Comment by ZhengyaoJiang** [comment]
So, it's a good news that the program could work on Mac OS.
