### ISSUE TITLE
data interval

### ISSUE THREAD

**Issue by laci84** [ZhengyaoJiang/PGPortfolio#13]
It seems to be hard coded 5 minute interval for data. Can it be configured for 1 minute or 1 hour / day by using other data sources?
Thanks!

**Comment by AhmMontasser** [comment]
i think it's not hard coded, there is a file called constants.py which contains declarations for more time intervals. Although the 5 minutes constant is given as a default value, you can change it while declaration.

**Comment by DexHunter** [comment]
> Can it be configured for 1 minute or 1 hour / day by using other data sources?

Sure, you can integrate broker's api to our framework. Replace `pgportfolio/marketdata/poloniex.py` with your desired broker. And change `period` at `HistoManager` from [globaldatamatrix](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/marketdata/globaldatamatrix.py#L20)

**Comment by ZhengyaoJiang** [comment]
Please note that 5 minutes is how the programme store the data, which is the minimum data interval of candle stick data on poloniex.
You can easily configure the interval of trading and observation by setting the "global_period" attribute in "net_config.json". The "global_period" should be  a integer of multiple of 300.

**Comment by laci84** [comment]
I have ohlc data with 1 min resolution in csv. How can I train a network on it? Custom loader, param config?

**Comment by ZhengyaoJiang** [comment]
> I have ohlc data with 1 min resolution in csv. How can I train a network on it? Custom loader, param config?

In that case, you just need to rewrite the globaldatamatrix (in particular, the get_global_data_panel method).
I think that won't be too difficult, just load csv using pandas and then transform it into a panel. While If you want to keep the functionality of assets selection work, you might also need to modify the select_coins method.

**Comment by pisiiki** [comment]
Hello, thanks for sharing the code.

I wonder if the self.__checkperiod call inside get_global_panel is not too restrictive. 
Would period%300 == 0 work or does it need more db code, sums, etc.?

Regards.

**Comment by ZhengyaoJiang** [comment]
> I wonder if the self.__checkperiod call inside get_global_panel is not too restrictive.
Would period%300 == 0 work or does it need more db code, sums, etc.?

Yes, the self.__checkperiod is already out of date.
I think period%300 == 0 should work on the new code.

**Comment by redzhepdx** [comment]
I want to ask a question about this sql query in the part of getting data from DB to pandas panel:
I think this query takes datas in range : [start_date + 300 sec, end_date - 300 sec]
It is ok for backtesting but I think need to update for real time testing, isn't it ?
```
sql = ("SELECT date+300 AS date_norm, close FROM History WHERE"
                               " date_norm>={start} and date_norm<={end}" 
                               " and date_norm%{period}=0 and coin=\"{coin}\"".format(
                               start=start, end=end, period=period, coin=coin))
```
