### ISSUE TITLE
ERROR:root:the sqlite error happend

### ISSUE THREAD

**Issue by Tylersuard** [ZhengyaoJiang/PGPortfolio#135]
This was in programlog:

INFO:root:select coins offline from 2017-04-03 12:28 to 2017-05-03 12:28
ERROR:root:the sqlite error happend
DEBUG:root:Selected coins are: []

Running in Colab, followed instructions in the User Guide.

**Comment by wenxixia** [comment]
Hi, Tyler, did you solve the problem?
