### ISSUE TITLE
new live data config settings

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#14]
Hello,
I have been trying to code the live trader, but 1 issue facing me is how to get live poloniex data while using the classes already implemented, of course i can hardcode 'generate_history_matrix' of the trader class to create the [3,11,31] data every tick manually but i am asking for the right way of doing it using the config settings since i didn't understand it.

i mean how to automate pulling the live data in sync. with the database.
Sorry for too much questions.
Regards

**Comment by ZhengyaoJiang** [comment]
Greetings,
There hasn't been a method that stores live data and gives input to the agent at the same time yet.
But you can implement it by yourself if you pleased to do so.

Regards

**Comment by AhmMontasser** [comment]
ok sure, 

thank you :)
