### ISSUE TITLE
Backtest trade by strategy, check fees vs coin value update 

### ISSUE THREAD

**Issue by doxav** [ZhengyaoJiang/PGPortfolio#15]
In BackTest, "omega" seems to be the vector wT storing the recommended new portfolio distribution at each step, "_last_omega" the latest/previous portfolio screenhost wT-1. So the system assumes to be able to sell at each step all the current coins of the portfolio and buy all "omega" reco, or at least the delta between omega & last_omega. This strong hypothesis (slippage/liquidity) is in your paper but shouldn't it check at least whether any coin qty adjustment would not cost more transaction fees than the expected value adjustment ?

**Comment by DexHunter** [comment]
> shouldn't it check at least whether any coin qty adjustment would cost more transaction fees than the expected value adjustment 

I think it's a good suggestion, especially for the live-trading. What do you think @ZhengyaoJiang

**Comment by doxav** [comment]
I could suggest an implementation but I don't understand the logic of `calculate_pv_after_commission` and especially: `mu1 = (1 - commission_rate * w0[0] - (2 * commission_rate - commission_rate ** 2) * np.sum(np.maximum(w0[1:] - mu1*w1[1:], 0))) / (1 - commission_rate * w1[0])`.

**Comment by DexHunter** [comment]
@doxav The function is based on our paper.
![screenshot_2017-12-09_01-08-29](https://user-images.githubusercontent.com/6930518/33758793-ce8ef138-dc3a-11e7-94af-36dd101ff619.png)

More details are on 2.3 transaction cost

**Comment by ZhengyaoJiang** [comment]
> I could suggest an implementation

Glad to hear your suggestion.

**Comment by doxav** [comment]
Ok, so I need to clarify the basis of this function:

In function (12): why do we multiply by (1 - Cs) considering that factor Ut should already include all transaction fees. 

![image](https://user-images.githubusercontent.com/1683325/33764294-25984f00-dc14-11e7-8d6e-d73a9bd2e828.png)

Again on function (13), same point but also another point on the cash reserve which could be used to buy new assets but the fees should only apply on the volume exchanged.

![image](https://user-images.githubusercontent.com/1683325/33764569-2f557526-dc15-11e7-9e4c-52fc15f8f740.png)

**Comment by kumkee** [comment]
For (12), let's consider only one asset. Before reallocation, you have total fund p', and p'.u after.
So the value of the asset in consideration is p'.w' before reallocation and p'.u.w after. You can think of p'.u.w as the target value want to achieve after selling.
Expression (12) without the (1-c) factor is then the difference between that asset's initial and target value. By performing this selling, we will get cash of an amount (1-c) times this difference.

If you do get (12), (13) follows the same logic.

**Comment by doxav** [comment]
On further consideration, it really depends on RL behavior. There is no transaction on which fees would exceed per coin adjustment but the matter is on movements between coins. It is difficult to arbitrate among coins movements (the 2 lowest adjustment?), an intuitive case is when the total portfolio adjustment costs more in fees than in expected gains. It would mean just to cancel adjustment when it lowers the capital at date ? On forecasted capital ? Still we don't know if RL reco is anticipating a forecasted capital growth (fees included).
