### ISSUE TITLE
cash (btc) is always zero

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#17]
In the new portfolio vector (raw omega) the cash (btc) is always zero. But this cannot be always the best choice: what if all the other currencies are losing value in a period? surely in this case the best choice is to move all the assets back to cash. 

In the code, the cash bias is initialized to zero just before the final softmax, so it cannot be anything else than zero. Was this intended?

**Comment by AhmMontasser** [comment]
among the possible coin choices there is a reversed_USDT coin mapping to BTC_USDT pair, which i believe is exactly what you say.

**Comment by DexHunter** [comment]
> In the new portfolio vector (raw omega) the cash (btc) is always zero. 

@ziofil Hi! Since the last activation is softmax, the voting will be adjusted according to the network. It all depends on the network. If the network thinks BTC is valuable it will just lower other assets' voting.

**Comment by DexHunter** [comment]
An example looks like this:

a = [0,1,2]
softmax(a) -> array([ 0.09003057,  0.24472847,  0.66524096])

b = [0,0.1,0.2]
softmax(b) -> array([ 0.30060961,  0.33222499,  0.3671654 ])


![screenshot_2017-12-13_15-35-41](https://user-images.githubusercontent.com/6930518/33926990-599f856a-e01b-11e7-801f-e846e53f5da7.png)

**Comment by ziofil** [comment]
@DexHunter  Oohhh.. I had missed that 😅
Thank you.

**Comment by DexHunter** [comment]
@ziofil No problem, I met this problem before. I think we will update the code using Variable later since I found using Variable seems to give better result. But will check with @ZhengyaoJiang  first
