### ISSUE TITLE
model response to coins trained on periods prior to their existance.

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#18]
Hello, 

I don't understand how the model response when a selected coin is not existing at the training period.

for example, choosing start date = 2015-07-01 and end date = 2017-11-01, BCH is chosen
The training/ backtest portfolio value decreases tremendously. is that because of the fact that BCH didn't exist most of that time ?

**Comment by ZhengyaoJiang** [comment]
The missing data in training set would be padded as 1.

**Comment by ZhengyaoJiang** [comment]
Yes, it is possible that 1s would affect the model performance but it is also possible that not taking new coins into consideration would let the agent loss chance to gain profit.
I'm not sure which is the real case. You can try to do an experiment if you are interested in this topic.
