### ISSUE TITLE
About training period and backtest period

### ISSUE THREAD

**Issue by d1210182010** [ZhengyaoJiang/PGPortfolio#19]
Hi
I am new to this project and try to do some deeper investigation for this framwork.
How could I set specific period for both training and backtesting, such as using 2010/01/01-2013/12/31 to train a model, and backtesting it (online training) from 2014/02/01 to 2014/12/31?
Thanks a lot!

**Comment by rpfeynman** [comment]
In the "net_config.json" file there are the settings for both the start and end date.
There's also the "test_portion" field, which allows you to choose how much of such set you want to use for backtesting.

**Comment by ZhengyaoJiang** [comment]
> How could I set specific period for both training and backtesting, such as using 2010/01/01-2013/12/31 to train a model, and backtesting it (online training) from 2014/02/01 to 2014/12/31?

As @rpfeynman said, you should first set "start_date" as "2010/01/01" and "end_date" as "2014/12/31", and then calculate the test portion.
