### ISSUE TITLE
Weight sharing in CNN

### ISSUE THREAD

**Issue by lytkarinskiy** [ZhengyaoJiang/PGPortfolio#20]
Hi everyone! First of all, thanks for the article and for sharing the code, you made a great job!

Now the question. In article it's said:

> Apart from weight-sharing among receptive fields in a feature map, which is a usual CNN characteristic, parameters are also shared between rows in an EIIE configuration.

But I couldn't find realization of this feature in code :( Can you help, or this idea was deprecated?

Thanks!

**Comment by ZhengyaoJiang** [comment]
> But I couldn't realization of this feature find it in code :( Can you help, or this idea was deprecated?

The CNN version of EIIE is implemented via a 2d fully-convolutional network. You can treat each row as a 1-d CNN and IIE.
The RNN version of EIIE is implemented by parameter sharing of tensorflow.
You can check them in the network.py.

**Comment by lytkarinskiy** [comment]
OK, thanks! I've checked the code already and it's all clear. I just thought about this feature from article as something special.
