### ISSUE TITLE
features besides ohlc

### ISSUE THREAD

**Issue by huminpurin** [ZhengyaoJiang/PGPortfolio#21]
I'm not familiar with reinforcement learning so this might be a newbie question. 
In other areas of data science, feature engineering can significantly affect the performance. As for quantitative trading, indicators (generated from ohlc data) like MACD usually can improve the performance of models. I would like to know did you use only ohlc prices for features on purpose (maybe it's not necessary in case of reinforcement learning) or is this considered as future work?

**Comment by DexHunter** [comment]
> did you use only ohlc prices for features on purpose

Quote from [our paper](https://arxiv.org/abs/1706.10059): 

> Nonetheless, all relevant information is believed, in the philosophy of technical traders (Charles et al., 2006; Lo et al., 2000), to be reflected in the prices of the assets, which are publicly available to the agent.

OHLC data is basically direct information and reflection from market, and most indicators are also generated from ohlc data as you said. So I think those information is probably enough for the agent. I also think we will test integrating indicators to the framework to see if better results are achieved, even though I doubt it's just a repeat of same information (or probably have a different emphasis).

**Comment by huminpurin** [comment]
Thanks! It looks like i missed that part in your paper.
