### ISSUE TITLE
reversed_USDT vs BTC

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#23]
Hello, 

In the code, i don't understand what is the difference between reversed_USDT and the cash (BTC). 

I supposed (USDT_BTC) which is actually BTC/USD is a mapping to just holding some weight in BTC 

Am i wrong ?

**Comment by DexHunter** [comment]
All the price is calculated in BTC, that's why BTC is always 1. `USDT` refers to Tether which is also a cryprtocurrency, so it's taken as an asset rather than cash(BTC). It's supposedly to provide some information about btc, but I don't think we treat it much differently than other cryptocurrencies under current framework.

**Comment by AhmMontasser** [comment]
great, it's reversed in trading actions, right ? 
so i sell BTC/USDT when i need to increase reversed_USDT weight and vice versa ?

**Comment by DexHunter** [comment]
reversed actually means the reverse of price because in poloniex for btc/usdt paris it's calculated in usdt, but we want to calculate in btc.

**Comment by AhmMontasser** [comment]
i understand this 
what i meant is, what is the end element for this coin after increasing the weight, is it BTC or USD ?

if the weight is 0.8 reversed_USDT in the new omega, after buying and selling should i end up with 0.8 the value in USD or in bitcoins ?

**Comment by DexHunter** [comment]
I am not sure if I understand your question correctly. But I don't think you can convert to USD in current framework directly. So the value is always in BTC (bitcoin).

**Comment by kumkee** [comment]
> if the weight is 0.8 reversed_USDT in the new omega, after buying and selling should i end up with 0.8 the value in USD or in bitcoins ? 

It will be USDT measured in BTC.

**Comment by AhmMontasser** [comment]
thanks a lot
