### ISSUE TITLE
Experience related to selected coins. 

### ISSUE THREAD

**Issue by AhmMontasser** [ZhengyaoJiang/PGPortfolio#31]
Hello, 

I noticed something while backtesting, the model new experience index is not following the previous backtesting if the selected coins is different. 

does that mean that model experience gained is only related to the coins it's trained on ?

**Comment by ZhengyaoJiang** [comment]
I didn't clearly understand your question.
What's the difference between “backtesting” and "previous backtesting"?

**Comment by AhmMontasser** [comment]
sorry for confusion, 
i meant that doing backtesting on different periods doesn't lead to the same sequence of experience index printed on this line
DEBUG:root:a new experience, indexed by 5283, was appended

for example, backtesting from 1/ 4 /2017 to 1/7/2017 has an experience index sequence different from backtesting from 1/8/2017 to 1/12/2017.

my question:
do the rolling training experience depends on the specific coins it was trained on ?

**Comment by ZhengyaoJiang** [comment]
Thanks for the clarification.
The rolling train index could depend on many things, say, the batch size, window size and the number of training samples.
One of the possible reasons here might be the dates represented by the string.
I'm not sure if the types of coins would affect.

**Comment by AhmMontasser** [comment]
Thank you for explaining
