### ISSUE TITLE
where is the nonlinearity?

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#32]
I'm trying to understand about the nonlinearity in your network (except for the final softmax): in the current version of `net_config.json`, you list the 3 layers of the network as one `ConvLayer`, one `EIIEDense` and one `EIIE_Output_WithW`. In neither of them there is an entry to specify the activation function, and the default one of conv_2d in TFLearn is 'linear', so are you using a nonlinearity between the layers?

**Comment by rpfeynman** [comment]
There are ReLU's in between the other layers

**Comment by ziofil** [comment]
What other layers?

**Comment by DexHunter** [comment]
Currently ReLU is used, you can see the [Line 52 of configprocess.py](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/tools/configprocess.py#L52) and Line 57 as well
