### ISSUE TITLE
Sharpe ratio as loss function

### ISSUE THREAD

**Issue by lytkarinskiy** [ZhengyaoJiang/PGPortfolio#33]
Hello all!

I wonder if you've tried to use Sharpe ratio directly to optimize portfolio selection? With controlling both mean and variance parts it seems to allow control risk management of portfolio selection and minimize drawdawn?

Although I saw in [literature](https://www.politesi.polimi.it/bitstream/10589/131892/1/MS_Thesis_Pierpaolo_Necchi.pdf) that risk sensitive policy is less effective than risk neutral one I want to hear your opinion.

Thanks!

**Comment by ZhengyaoJiang** [comment]
Greetings,
This question is related to our recent unpublished work. I'm sorry that I cannot discuss too much the topic.
However, what I can tell is using Sharpe ratio directly here won't work.

Regards
zhengyao

**Comment by lytkarinskiy** [comment]
Wow, besides the work already've been done it's a huge next step!
Can you tell any possible date we can read the paper? =)

Andrey

**Comment by ZhengyaoJiang** [comment]
I think next year.
Not sure about the exact date yet.

Zhengyao

**Comment by akaniklaus** [comment]
@lytkarinskiy Found some example implementations below, why don't you try to integrate that for us?
https://github.com/TenzinDJ/AI_for_Finance
https://github.com/SergeOlivierP/agentF
https://github.com/OlegMitsik/AA228_Project
