### ISSUE TITLE
Question about "algo" command line options

### ISSUE THREAD

**Issue by PumpkingWok** [ZhengyaoJiang/PGPortfolio#34]
Hi there,

First of all i would like to thank you to have shared the code, it is a very good work, also the code is clear to understand.I had followed your first paper too and implemented a live trading agent but without lucky.
This paper seems more interesting, also takes into consideration the transaction fees.

It's my question:  Can't i use algo option for selecting specific algo when the mode is train ? is it always train with all algos with `train_all` command ?
In `main.py` i think there is a typing error (options.train_floder) on line 58.

Thank you very much in advance.

**Comment by ZhengyaoJiang** [comment]
Greetings,
Thanks for your consistent interest in our work. Using the DRL agent instead of the simple model in live-trading can be a quite challenging task, so please be careful.

It hasn't implemented yet but you can try to do so by using train_one if you like.

zhengyao

**Comment by PumpkingWok** [comment]
Hi zhengyao,

Thank you for the reply and suggestions, i would like to understand the whole code before to attempt to do live trading again.
I would have another question if i can ask it: When the NN retrieve the classification of portfolio distribution for each timestamp, most of the time almost all coins have a very small percent of total portfolio, less than 10^-3/10^-4, it was a problem for me during live trading, poloniex for instance does not permit to buy value too little of a coin.I have used some approximation but it has become like a single asset distribution problem.Maybe with a lot of funds this problem disappear.

Thank you again, have a nice day.

**Comment by ZhengyaoJiang** [comment]
> I have used some approximation but it has become like a single asset distribution problem.

Yes, that's what the agent would do.
