### ISSUE TITLE
Stock Application

### ISSUE THREAD

**Issue by joaosalvado10** [ZhengyaoJiang/PGPortfolio#35]
Hello, I am interested in applying this solution to stock markets instead of cryptocurrencies. I Have a csv file containing the Open High Low Close of each one of my stocks. Let's say I Have 5 stocks for example.
I would like to know how should I proceed in order to adapt this solution to the stock market instead.

Really nice project.
Thank you

**Comment by ZhengyaoJiang** [comment]
Hi there,
I think you need first modify "globaldatamatrix.py".
The most important interface is `get_global_panel()`.
The csv should be transformed into a pandas panel whose axis are "[feature, coin, time]".

zhengyao

**Comment by joaosalvado10** [comment]
@ZhengyaoJiang hello, 
I have been trying to modify it still I could not find a way to do it.
Do  you plan to do add this type of feature?

**Comment by ZhengyaoJiang** [comment]
> Where is the main loop of Reinforcement learning?

The main loop of training is in `tradertrainer`.

> And how would I use the model to predict the action it if I receive new prices?

You can use the `decide_by_history` method of `nnagent`

**Comment by chankeypathak** [comment]
@ZhengyaoJiang , @joaosalvado10 
Has this been implemented? If yes then could you please share an example of the same? Thanks.
