### ISSUE TITLE
Portfolio weights (real time)

### ISSUE THREAD

**Issue by mhastingsai** [ZhengyaoJiang/PGPortfolio#37]
First, congratulations on the great work!

I would like to know how to access the date frame of updated weights every 30 minutes for trades in real time. Currently I have some models in R, already operating online, but I do not have much knowledge in Python. Anyone would like to collaborate? All the methods of access to the exchanges and the launching of orders are already developed.

yukie

**Comment by cemreefe** [comment]
Hi, may I ask how you solved this issue?

**Comment by franklili3** [comment]
not,yet.


------------------
世界充满希望 机会就在眼前  李力


 





------------------ 原始邮件 ------------------
发件人: "Cemre"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 下午3:25
收件人: "ZhengyaoJiang/PGPortfolio"<PGPortfolio@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [ZhengyaoJiang/PGPortfolio] Portfolio weights (real time) (#37)




Hi, may I ask how you solved this issue?
