### ISSUE TITLE
Poloniex API no longer accessible programmatically

### ISSUE THREAD

**Issue by ielashi** [ZhengyaoJiang/PGPortfolio#4]
Looks like the Poloniex API is no longer accessible programmatically. I'll look into alternative APIs and will try to follow up with a pull request for this.

**Comment by ZhengyaoJiang** [comment]
> Looks like the Poloniex API is no longer accessible programmatically.

Did you mean you can't download training data?

**Comment by ielashi** [comment]
Yes, download requests give a 403 now because Poloniex added a CAPTCHA to the API calls.

**Comment by ZhengyaoJiang** [comment]
Really? I've also tried to download training data just now, nothing strange happened though.

**Comment by ielashi** [comment]
Interesting. I just tried it through a US proxy and it works. I guess that's a regional restriction that Poloniex has rolled out. Never mind then.

**Comment by DexHunter** [comment]
Besides, you can use [python-poloniex](https://github.com/s4w3d0ff/python-poloniex) which supports private command as well. The latest version should cover proxy. You can check [this](https://github.com/s4w3d0ff/python-poloniex/issues/167) as well.

**Comment by StarJu** [comment]
The key is many proxies not work already in mainland China. So the data is still unreachable.
