### ISSUE TITLE
Extending the data into the past

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#40]
Hi,

If a currency doesn't have enough data before a certain point in time, how do you extend it? With constant values? if so how do you pick the value?

I think I understood that you use the oldest non-NaN value, but some currencies have a crazy initial spike before settling very close to zero, so I'm not sure that's what you actually do.

**Comment by DexHunter** [comment]
possible #18 related

**Comment by ziofil** [comment]
Ooh, thank you, I had not seen that. Solved.
