### ISSUE TITLE
better portfolio reallocation

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#41]
The current portfolio reallocation step is divided into two parts: selling the necessary assets to convert them into BTC, and then buying the new assets. I'm wondering if it would be possible to adopt a more clever strategy.

For example, if the current portfolio is [0,1,0] and the desired one is [0,0,1], we need to pay 0.025% of fees for selling and another 0.025% for buying. But wouldn't it be more efficient to exchange the second and third assets directly, without going through BTC and so pay only 0.025% once?

**Comment by kumkee** [comment]
> But wouldn't it be more efficient to exchange the second and third assets directly, 

That will require the exchange to have the trading pair for these two assets. For most pairs, they are not directly tradable on Poloniex or many other major exchanges. However, in forex markets, mutual pairs are more common.

**Comment by ziofil** [comment]
True, I did not consider that. So if a pair exists it could be used, but this I suppose would make it harder to compute mu.

**Comment by kumkee** [comment]
> this I suppose would make it harder to compute mu.

It would be a different way of calculating mu for sure, but not necessarily harder. What becomes more difficult might be the implementations of the back-test simulation engine and the live-trading logic.

Side note: training a machine with harsher conditions (a more pessimistic mu for example) is desirable if you want the machine to be more cautious to market risks.
