### ISSUE TITLE
Eq. (16)

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#42]
Surely you meant 1 - [current equation]?
As it is now, if there were no change in the portfolio vector, mu_guess would be zero, which is a terrible guess (mu_t is 1). Also in the case in which there are no fees (c=0), you'd guess 0.

**Comment by kumkee** [comment]
> Surely you meant 1 - [current equation]?

Yes, you are right. Thanks for the correction.

**Comment by ziofil** [comment]
No prob 👍
