### ISSUE TITLE
ForwardTest class

### ISSUE THREAD

**Issue by einarbmag** [ZhengyaoJiang/PGPortfolio#44]
Hi, thank you for your excellent work, this is very interesting stuff. 

I am eager to test this on the live market, but having trouble moving from backtesting to forwardtesting. Any chance that an update with a ForwardTest class is on the way, or that you could advise on how to implement it? I understand it roughly, i.e. the generate_history_matrix( ) function needs to update the datamatrix with the newest market data (with "online" = True in the config file), and return that. And the trade_by_strategy( ) clearly needs a slight rewriting compared to BackTest as we don't know the future price. Any help on how to correctly return the newest market data would be appreciated.

**Comment by DexHunter** [comment]
possible related to [this comment](https://github.com/ZhengyaoJiang/PGPortfolio/issues/11#issuecomment-348517550)

**Comment by gittaylor** [comment]
Yes, I am having the same problem.  I was able to modify the backtesting class to get new data, but tflearn will not accept the new history for training.  Any help would be appreciated.

**Comment by redzhepdx** [comment]
In backtesting there are two options to test model online or offline. 

**Online : Takes data from poloniex and updates database
Offline : Using pre-collected datas in Data.db**

Backtesting module using rollingtrainer's datamatrix and it takes all datas from database at the begginning of the backtest.

But I couldn't find a way to get new data and process it .
It is using day based date to take data in given day based interval. 
Is there any module to update database dynamically for livetrading without resetting learning of the model ?

**Comment by ZhengyaoJiang** [comment]
> Is there any module to update database dynamically for livetrading without resetting learning of the model ?

A simple(while not elegant) method is to append new data to the global_data (Panel in the memory) and modify all the related indexes.

**Comment by redzhepdx** [comment]
I am doing this for real time data ;
- last input X: global_data[: , :, -window_size:]
- apply action according to X
- Wait n-minutes
- get input again
- y : newX[:, :, -1] / newX[:, :, -2]
But couldn't solve the how to use thid x, y data to update RL agent.
I think RL training must be always active for the understand every new situation , but it seems it don't train model in backtesting part adding None object to experience tracker module.
Also thank you for first fast reply :)

**Comment by einarbmag** [comment]
Thank you for the hints @ZhengyaoJiang and @redzhepdx, will give it another go now!

**Comment by insaneKane** [comment]
has there been any progress on this ?

Ill probably just try to replicate the steps @einarbmag, @redzhepdx and @ZhengyaoJiang outlined to modify and use global_data live but if someone has found a more sophisticated way im all ears :)

**Comment by DoktorDaveJoos** [comment]
related on @ZhengyaoJiang 's answer:
in trade/backtest.py this
**omega_grads = np.subtract(self._last_omega, omega)**
should be the transaction vector, right?
