### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by ziofil** [ZhengyaoJiang/PGPortfolio#49]
How long does it take to properly train the agent, on your machines? (I have a laptop without a GPU)

**Comment by DexHunter** [comment]
It depends on the steps and whether you include rolling train and etc. But normally it takes about 5 - 15 min on my laptop (Intel i5-7300HQ CPU @ 2.50GHz) to finish training.

**Comment by raquelredo** [comment]
@DexHunter  can you share specific hyperparameters for getting this 5 minutes training. I tried different configurations and it lasts hours for me.

**Comment by DexHunter** [comment]
@raquelredo Sure. Simply change [steps](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/net_config.json#L9) to 8000 and [batch size](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/net_config.json#L11) to 1000, and remove rolling train. I finished the run in 130.088179111 seconds. The test result is 14.985277 BTC. 

If you want even faster, just change raio of steps/batch_size. But results could worsen. So I don't suggest you to do that.

**Comment by raquelredo** [comment]
Thanks! I 'll run it again
