### ISSUE TITLE
Issue about train_summary.csv

### ISSUE THREAD

**Issue by EstelleHuang666** [ZhengyaoJiang/PGPortfolio#5]
Hi, I am following your instruction on user_guide.md. You mention the file named train_summary and train_summary.csv from time to time which I think store the results of training. However, I could not find  in your project where you generate such a file. Neither could I generate one by following your instruction. Look forward to your answer. Thank you so much!

**Comment by DexHunter** [comment]
@EstelleHuang666 Hi, there! What steps have you tried? The `train_summary` will be generated only after you finish the training.

An example operation should look something like:
1. config `net_config.json` under `./pgportfolio`
2. `python main.py --mode=generate --repeat=1`
3. `python main.py --mode=train --processes=1`

Besides, if you are looking for the code. It is [here](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/learn/tradertrainer.py#L205)

**Comment by ZhengyaoJiang** [comment]
> Neither could I generate one by following your instruction. Look forward to your answer. 

As @DexHunter said, if you finish training, it should be generated under the `train_package` folder.

**Comment by EstelleHuang666** [comment]
Such a dumb - -#... Great thanks for your explanation!

**Comment by mertovun** [comment]
Hi. I am also having a problem with generating the train_summary.csv file after `python main.py --mode=train --processes=1` step although it does not respond any errors. 
`net_config.json` replicate folders seem to be successfully generated under train_package folder after `python main.py --mode=generate --repeat=1` command. I also downloaded the data beforehand using `python main.py --mode=download_data` command as suggested. But I could not obtain the csv file.
Should I  somehow modify the config file for the first run or is there something else missing?
Thanks.

**Comment by EstelleHuang666** [comment]
Sorry I don't know much about your problem. But maybe you can try the following method I once used.

Under the path "PGportfolio/pgportfolio/autotrain/training.py", it has:
`
for dir in all_subdir:
        # train only if the log dir does not exist
        if not str.isdigit(dir):
            return
        # NOTE: logfile is for compatibility reason
        if not (os.path.isdir("./"+train_dir+"/"+dir+"/tensorboard") or os.path.isdir("./"+train_dir+"/"+dir+"/logfile")):
            p = Process(target=train_one, args=(
                "./" + train_dir + "/" + dir + "/netfile",
                load_config(dir),
                "./" + train_dir + "/" + dir + "/tensorboard",
                dir, logfile_level, console_level, device))
            p.start()
            pool.append(p)
        else:
            continue
`
The first “if” check whether the names of folders under this directory are digital or not. However, for me I ran it on macOS, it would generate a hidden folder named ".DS_Store" automatically. And according to the order of ASCII, this folder would be checked first before those folders named digitally which we really need. Then this function returns directly without reading in any data.

What you can do, I think is: 
(1) Delete the folder ".DS_Store" manually;
(2)Change the "return" under the first if into "continue".

**Comment by mertovun** [comment]
@EstelleHuang666 it turned out that it is the exact reason of my problem. Thank you so much! Problem solved.
