### ISSUE TITLE
Downloading data

### ISSUE THREAD

**Issue by leahwu** [ZhengyaoJiang/PGPortfolio#52]
Hi!

First of all, thank you for your code.

I ran into an error when I wanted to download the data online when training.

An error at "Poloniex.py" occurs with:
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>`

I have already used a global VPN whose server is in LA. And everything works fine when I download data with `python main.py --mode=download_data`.

So I think it is not a problem with the connection to Poloniex (although I am in China). 

Could anyone help me with this issue? Thanks

**Comment by DexHunter** [comment]
Maybe you can check #4 

Besides, you can download data first and then training. As you said, there doesn't seem to be a problem
