### ISSUE TITLE
Backtesting question

### ISSUE THREAD

**Issue by sahpat229** [ZhengyaoJiang/PGPortfolio#57]
Hi, I'm wondering why for Backtesting, on line 96 of trader.py, the model's output of the asset allocation isn't fed in as the "last_w" for the next time step:
https://github.com/ZhengyaoJiang/PGPortfolio/blob/4ccd4d21d09973fa49d747041871e852aca9eded/pgportfolio/trade/trader.py#L96

I'm tracing the call to backtest.start_trading() from line 218 of tradertrainer.py:
https://github.com/ZhengyaoJiang/PGPortfolio/blob/4ccd4d21d09973fa49d747041871e852aca9eded/pgportfolio/learn/tradertrainer.py#L218

Thank you

**Comment by DexHunter** [comment]
> the model's output of the asset allocation isn't fed in as the "last_w" for the next time step:

The `last_omega` is `last_w`. And the training is different from backtesting.

https://github.com/ZhengyaoJiang/PGPortfolio/blob/4ccd4d21d09973fa49d747041871e852aca9eded/pgportfolio/trade/trader.py#L91-L92

**Comment by sahpat229** [comment]
Okay, I see my misunderstanding.  Thanks for responding, I appreciate your help!
