### ISSUE TITLE
Depth of EIIE_Dense layer

### ISSUE THREAD

**Issue by WojciechMigda** [ZhengyaoJiang/PGPortfolio#60]
Hi,
EIEE_Dense layer specification in `net_config.json` has depth hard coded as 10. Unless my understanding is fundamentally wrong, this value is directly related to the number of traded assets. Hence, should it be dynamically determined in `learn/network.py` from the input tensor dimension instead?

**Comment by DexHunter** [comment]
> Unless my understanding is fundamentally wrong, this value is directly related to the number of traded assets. 

The `filter number` of EIIE_Dense is not related to the number of traded assets.  The number of traded assets is determined by `coin number` (or `self._rows + 1` at `network.py`) .

**Comment by dlacombejr** [comment]
> EIEE_Dense layer specification in `net_config.json` has depth hard coded as 10.

The number that you refer to (10) is the number of filters in that layer, not the depth. Depth is calculated automatically based on the number of filters in the first convolutional layer (default to 3). The other filter dimensions are set as `[1, width]`, where width is the resulting length of the tensor on the 2nd dimension after the first convolutional layer.
