### ISSUE TITLE
select gpu unit

### ISSUE THREAD

**Issue by Amarchuk** [ZhengyaoJiang/PGPortfolio#65]
Hi! 

As I understand from User Guide, recent GPU support just make you able to train more models at the same time. Is there a simple way to choose which gpu unit to use if I have more than one?

**Comment by DexHunter** [comment]
The framework by default uses all the GPU. For single GPU usage, you can check [tensorflow page](https://www.tensorflow.org/programmers_guide/using_gpu#manual_device_placement)

**Comment by Amarchuk** [comment]
Thanks for the reference!

Are you sure about all GPUs usage? I have several of them installed, but when running 1/2/6 training processes I get near the same time results in both `--device=cpu` and `--device=gpu` modes. It is even more strange because CPU has only two cores. Should I expect better performance or maybe I miss something important?

**Comment by DexHunter** [comment]
Hmm.. You need to give your environment. I can't analyse the problem without further information. Besides, I suggest you check stackoverflow or other forums first since they generally have more information on this topic and very easy to find repeated problem.

**Comment by Amarchuk** [comment]
@DexHunter Sure, I don't expect you to teach me how to work with tf/gpu/etc :D 
Just check my common sense for the recent implementation and your answers provide me enough information on that. Thank you
