### ISSUE TITLE
Nothing happens when training the model. (Mac OS X)

### ISSUE THREAD

**Issue by laygr** [ZhengyaoJiang/PGPortfolio#72]
I'm typing:

`python main.py --mode=train --processes=1`

and the terminal just returns a new promt. programlog has this:

> INFO:root:select coins offline from 2017-04-03 12:28 to 2017-05-03 12:28
DEBUG:root:Selected coins are: ['ETH', 'LTC', 'XRP', 'reversed_USDT', 'ETC', 'DASH', 'XMR', 'XEM', 'FCT', 'GNT', 'ZEC']

I typed priorly `python main.py --mode=generate --repeat=1`

I had already copy the Data.db in the correct directory.

Initially, I got this error: 

> Exception: Have to be online

But I followed the suggestion in #46 (set end_date to one day earlier) and then I'm getting the described behavior.

<img width="942" alt="screen shot 2018-03-24 at 10 13 10 pm" src="https://user-images.githubusercontent.com/1335399/37871665-98c95a06-2fb0-11e8-9ce3-b684c4e0e178.png">

**Comment by DexHunter** [comment]
Maybe you can refer to #12?

**Comment by laygr** [comment]
I tried to set online=false after generating as suggested in #12, but got the same behavior. I'm yet to try with v1

**Comment by laygr** [comment]
Nah, tried with v1 and still got the same behavior. Is there a suggested way of debugging?

**Comment by laygr** [comment]
Ah, got it! I debugged it with pycharm. The problem is that it is taking the hidden .DS_Store (an OS X thing) file as the subdirectory to use, instead of the dir "/1"
