### ISSUE TITLE
Long/short equity

### ISSUE THREAD

**Issue by tms1337** [ZhengyaoJiang/PGPortfolio#8]
First off, thanks for publishing the paper as well as the code, it will help me a lot.
 
Now for the question. As I understand the layer before softmax offers sort of 'ranking' of coins, where higher rank can be interpreted as higher possibility of price rise. 

I planned on editing the code to use this layer as ranking for long/short equity strategy which hedges more against the market movements. I would test it on this years' data since a lot of things happened and would compare it against the current 'long only' method that is provided in the paper.

I do not need any technical help yet, but from the theoretical perspective what are your thoughts on this, since you probably have more insight on what your network is capable of? Or have you tried similar things so far?

**Comment by DexHunter** [comment]
@tms1337 Hi! Thanks for proposal. Shorting is definitely plausible. Besides, you can also have leverage. I think we will release it in the next version.

**Comment by tms1337** [comment]
Great this can grow into a nice framework or starting point over time. 

Are there any info on the next version date?

**Comment by DexHunter** [comment]
Probably around/after January 2018
