### ISSUE TITLE
Poloniex public API is returning 403 forbidden error

### ISSUE THREAD

**Issue by LohithBlaze** [ZhengyaoJiang/PGPortfolio#83]
Hi,

I was trying to evaluate the algorithm on the new dataset by downloading new data from poloniex API, but when I checked their API, they have added a captcha for each public API request.

Is there a way to bypass this error?
Otherwise can you suggest me the changes that need to be done to support other exchanges?

**Comment by DexHunter** [comment]
Please refer to https://github.com/ZhengyaoJiang/PGPortfolio/issues/4#issuecomment-346083120
