### ISSUE TITLE
ValueError during training

### ISSUE THREAD

**Issue by jpa99** [ZhengyaoJiang/PGPortfolio#85]
Running on Python 3.4.3, after I call `python3 main.py --mode=train --processes=1`, I get the following error:

ValueError: the length of selected coins 0 is not equal to expected 11

Perhaps this an issue with my version of Python?

**Comment by jpa99** [comment]
When I try executing `python3 main.py --mode=download_data`,  get the following:

urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:600)>

**Comment by DexHunter** [comment]
What about using the data from release? https://github.com/ZhengyaoJiang/PGPortfolio/releases

**Comment by jpa99** [comment]
Sorry, yet I meant I've set the "online" parameter to false

**Comment by DexHunter** [comment]
[The error](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/marketdata/globaldatamatrix.py#L180) still indicates there are something wrong with your data. Please refer to user_guide.

**Comment by jpa99** [comment]
Ok, I'm now able to download the data successfully, but when attempting to backtest using

I get:

**Comment by jpa99** [comment]
Nevermind, training seems to be working. Thanks for your help!

**Comment by DexHunter** [comment]
I see why you are confused, I added a note to the `user_guide`. You need to train before you backtest. I'll close it now if you don't mind.
