### ISSUE TITLE
Not an issue but suggestion for data

### ISSUE THREAD

**Issue by StarJu** [ZhengyaoJiang/PGPortfolio#9]
Hi yaojiang,
    As you know, google Captcha not work in China, so the data in poloniex.com I cannot download successfully. Could you upload those data for a while?

**Comment by DexHunter** [comment]
#4 related

**Comment by ZhengyaoJiang** [comment]
> Could you upload those data for a while

Sure.

**Comment by ZhengyaoJiang** [comment]
Please check the first release, there is `Data.db`.
