### ISSUE TITLE
Confliction between paper and real code

### ISSUE THREAD

**Issue by wujun** [ZhengyaoJiang/PGPortfolio#92]
First of all, thanks to all your guy's great job on PGPortfolio project! it's really awesome. I've been reading your paper and codes for months in my spare time. Now, I found a confliction between your paper and real code.
In your paper(v2), you said the input Xt must be the stacking of the three normalized price matrices(page 9) which are combined with Vt, Vt(hi) and Vt(lo). They are the normalized price matrices. But in real code(pgportfolio/marketdata/datamatrices.py), the method __pack_samples(self, indexs) only returns Xt by 
M[:, : , :,  : -1]  which is the last elements in the matrix that need a place to normalize the raw data but I can't find it. Would like to you give me any hint to make me more clear?

**Comment by DexHunter** [comment]
@wujun thank you for your interest in this work. Normalization is a bit subtle in implementation, it's in the [network.py](https://github.com/ZhengyaoJiang/PGPortfolio/blob/master/pgportfolio/learn/network.py#L47).

**Comment by wujun** [comment]
Thanks a lot, I catch it:)
